// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfPgyTZlhbtIdVyAd6wYvGTpKOfqWaRQA',
    appId: '1:890147328714:web:c39a7640f6367a7a73da33',
    messagingSenderId: '890147328714',
    projectId: 'task-flutter-98f32',
    authDomain: 'task-flutter-98f32.firebaseapp.com',
    storageBucket: 'task-flutter-98f32.appspot.com',
    measurementId: 'G-YFJGRMDYY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ3tiht4HEOPvi2T9iOfnfJ8LwrtAzlaU',
    appId: '1:890147328714:android:91ccfc51bc99203973da33',
    messagingSenderId: '890147328714',
    projectId: 'task-flutter-98f32',
    storageBucket: 'task-flutter-98f32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAECjhBezSJsWOVw-mcQk2Tr25bBu7KFE',
    appId: '1:890147328714:ios:5c60fc2a3bff3c4e73da33',
    messagingSenderId: '890147328714',
    projectId: 'task-flutter-98f32',
    storageBucket: 'task-flutter-98f32.appspot.com',
    iosClientId: '890147328714-vphm4l24c2s62653sccs8na7dbnhjqcl.apps.googleusercontent.com',
    iosBundleId: 'com.example.sampleGithub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAECjhBezSJsWOVw-mcQk2Tr25bBu7KFE',
    appId: '1:890147328714:ios:5c60fc2a3bff3c4e73da33',
    messagingSenderId: '890147328714',
    projectId: 'task-flutter-98f32',
    storageBucket: 'task-flutter-98f32.appspot.com',
    iosClientId: '890147328714-vphm4l24c2s62653sccs8na7dbnhjqcl.apps.googleusercontent.com',
    iosBundleId: 'com.example.sampleGithub',
  );
}
